title: Dawnette Crew
logo: Dawn-portfolio.jpg
tagline: Educator turned inspiring developer, blending creativity and problem-solving to design intuitive, user-focused digital tools.
#show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0

sass:
  style: compressed

<link rel="stylesheet" href="{{ '/assets/css/style.css' | relative_url }}">
