title: Dawnette Crew
logo:/https://github.com/dawnettecrew/portfolio/blob/main/Dawn%20portfolio.jpg
tagline: Educator turned inspiring developer, blending creativity and problem-solving to design intuitive, user-focused digital tools.
#show_downloads: true
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
